### ISSUE TITLE
Does facebook-plugins work with react@15.1.0

### ISSUE THREAD

**Issue by mnazim** [studiofrenetic/facebook-plugins#1]
Hello

Is there any plan to upgrade to support react@15.1.0
I get peerInvalid error when I try to install it in my project which has react@15.1.0

**Comment by MathieuDoyon** [comment]
I'll try to update this week.

**Comment by glennreyes** [comment]
Works seemlessly with `15.3.1`.

**Comment by MathieuDoyon** [comment]
thanks @glennreyes
